# Numpy: Faster And Efficient Computing Than Pure Python

### <b>Objective</b>: To see how implementation of numpy for basic tasks improves performance of pure python

In [1]:
import numpy as np

### 1. Elementwise operations on array

Numpy provides faster elementwise operations by implementing c-level vectorization

Numpy uses something called ufuncs (aka universal functions)<br>
which support a whole family of arithmetic operations like + - * / % // **<br>
bitwise operators, comparison operators, trigonometric, exponential etc

In [2]:
# normal for loop for adding
a = list(range(100000))
%timeit [i+5 for i in a]

8.13 ms ± 463 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
# numpy vectorized addition
b = np.arange(100000)
%timeit b+5

57.7 µs ± 3.54 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 2. Numpy Aggregation

functions like np.min, np.max, np.average, np.argmax run much faster than in-built python min, max functions

In [4]:
from random import random
a = [random() for i in range(100000)]

In [5]:
%timeit min(a)

1.96 ms ± 73.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a_np = np.array(a)
%timeit np.min(a_np)

52.5 µs ± 3.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
%timeit sum(a)

590 µs ± 6.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%timeit np.sum(a_np)

43.2 µs ± 339 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### 3. Broadcasting - effortless multidimensional array operations

Add a scalar to vector<br>
Add vector to matrix<br>
Add vectors differ in dimension

In [9]:
# 1.Add scalar to vector
np.ones(3) + 5

array([6., 6., 6.])

In [10]:
# 2.Add vector to matrix
np.ones(9).reshape(3,3) + np.array([9,68,47])

array([[10., 69., 48.],
       [10., 69., 48.],
       [10., 69., 48.]])

In [11]:
# 3.Add vectors in different dimensions
np.ones(3).reshape(3,1) + np.array([4, 9 ,6])

array([[ 5., 10.,  7.],
       [ 5., 10.,  7.],
       [ 5., 10.,  7.]])

### 4. Numpy's slicing. masking, fancy indexing

In [12]:
# 1.Indexing is same as python indexing

In [13]:
# 2.Masking...it is indexing an array by using another array
a = np.array([4, 1, 2, 9, 7, 8])
mask = np.array([True,False,True,False,True,True])

In [14]:
a[mask]

array([4, 2, 7, 8])

In [15]:
mask = (a<2) | (a>6)

In [16]:
a[mask]

array([1, 9, 7, 8])

### 5. Some examples

### addition

sequentially adding 10000 to each element in list

In [17]:
x_list = list(range(1000000))

In [18]:
%%timeit
# using for loop
for idx,item in enumerate(x_list):
    x_list[idx] = item + 10000

112 ms ± 6.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
# using list comprehension
x_list = list(range(1000000))
%timeit new_x_list = [x+10000 for x in x_list]

69.4 ms ± 265 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
# using numpy vectorized addition
x_np = np.arange(1000000)
%timeit new_np_x = x_np + 10000

1.66 ms ± 4.78 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### product

sequentially multiplying each element by 10000

In [21]:
x_list = list(range(1000000))

In [22]:
%timeit new_x_list = [x*10000 for x in x_list]

74.8 ms ± 186 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
x_np = np.array(x_list)

In [24]:
%timeit x_np*10000

1.72 ms ± 133 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### matrix multiplication

multiplying 4x3 * 3x4 matrices

In [25]:
a = [[1,2,2],
     [4,3,2],
     [5,8,1],
     [4,5,2]]

In [26]:
b = [[4,7,8,1],
     [0,7,4,1],
     [9,7,1,2]]

In [27]:
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

In [28]:
%%timeit
#using 2 for loops
for idx,i in enumerate(a):
    for jdx,j in enumerate(zip(*b)):
        result[idx][jdx] = sum([x*y for x,y in zip(i,j)])

17.8 µs ± 2.05 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
# using numpy
a_np = np.array(a)
b_np = np.array(b)
%timeit c = np.dot(a_np,b_np)

1.71 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### sample function case: integer vs numpy array

In [30]:
def compute_product_till(a):
    k = 1
    for i in range(1,a):
        k = k * i
    return k

In [31]:
def np_compute_product_till(a):
    k = np.array([1])
    for i in range(1,a):
        k = k * i
    return k

In [32]:
%timeit compute_product_till(10000)

23.4 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [33]:
%timeit np_compute_product_till(10000)

9.85 ms ± 915 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
